name: Pulumi

on:
  push:
    branches: 
      - 'feature/*'
      - 'patch/*'
      - 'bugfix/*'

env:
  RUN_NUMBER: ${{ github.run_number }}

jobs:
  up:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout code
        
      - uses: pulumi/actions@v3
        name: Preview Pulumi changes
        with:
          command: preview
          stack-name: dev
          work-dir: ./iac/pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}